import os, sys
from src import serviceDirs, serviceFiles, consolidate


""" 
    This script is designed by Mouad Maaziz to process and organize data from spreadsheets generated by ArcGIS closestFacility
which calculates the shortes distance between 11k locality to various services, using a naming convention.
The spreadsheets should be named in the format "service_localityType_year.xls" where "service" is the type of service,
"localityType" is the type of locality, and "year" is the year of data collection. 
    The script will extract the service, the corresponding id of the facility, locality type, and year information from the 
spreadsheet and use this information to group and merge the data from the spreadsheets. The script will be able to group 
the spreadsheets by their service, locality type, and year and merge the data from all the spreadsheets into a single spreadsheet.
"""


# Setting the path to the directory containing the spreadsheets and the directory for the results.
try:
    pwd = data_file = os.path.join(sys._MEIPASS, 'input')
except Exception as e:
    pwd = os.path.join(os.path.dirname(os.path.abspath(__file__)),'input')

results_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'results')


def main():
    print("Did you make sure that:\n1.The files' format is:\tservice_localiteType_year.xls/xlsx\n2.This script is located next to the 'input' directory containing the excel files.")
    if (input("confirm [Y] Yes  [N] No ?  ")[0].lower()=='y'):
        print("Launching ...")
        serviceDirs.serviceDirs(pwd,results_dir)
        print("=======\tCreated service dirs")
        serviceFiles.serviceFiles(results_dir)
        print("=======\t file_per_service generated")
        consolidate.consolidate(results_dir)
        print("=======\tSuccessful")
        print("============\tThank you for using this script, hope it helped\t=================")


if __name__ == '__main__':
    main()